source_stream_name         = "stg-ride_events"
output_stream_name         = "stg-ride_predictions"
model_bucket               = "stg-mlflow-models-code-pilugin"
lambda_function_local_path = "../lambda_function.py"
docker_image_local_path    = "../Dockerfile"
ecr_repo_name              = "stg-stream_model_duration"
lambda_function_name       = "stg-prediction_lambda"
