deployments:
- name: taxi_local_data
  entrypoint: 3_4_orchestrate.py:main_flow
  work_pool:
    name: mlops_pool
- name: taxi_s3_data
  entrypoint: 3_5_orchestrate_s3.py:main_flow_s3
  work_pool:
    name: mlops_pool
